"""initial migration

Revision ID: bdb2e742e062
Revises: 90816bc247c2
Create Date: 2025-08-19 17:50:10.123206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb2e742e062'
down_revision: Union[str, Sequence[str], None] = '90816bc247c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gsc_metrics')
    op.drop_table('content_keywords')
    op.drop_index('ix_keywords_keyword', table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('content_item_clusters')
    op.drop_index('ix_clusters_code', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index('ix_internal_links_source', table_name='internal_links')
    op.drop_index('ix_internal_links_target', table_name='internal_links')
    op.drop_table('internal_links')
    op.drop_index('ix_content_items_category', table_name='content_items')
    op.drop_index('ix_content_items_publish_date', table_name='content_items')
    op.drop_index('ix_content_items_slug', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=128), nullable=True),
    sa.Column('pillar', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('primary_keyword', sa.VARCHAR(length=255), nullable=True),
    sa.Column('secondary_keywords', sa.TEXT(), nullable=True),
    sa.Column('topic_authority_score', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_content_items_slug', 'content_items', ['slug'], unique=1)
    op.create_index('ix_content_items_publish_date', 'content_items', ['publish_date'], unique=False)
    op.create_index('ix_content_items_category', 'content_items', ['category'], unique=False)
    op.create_table('internal_links',
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('anchor_text', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_index('ix_internal_links_target', 'internal_links', ['target_id'], unique=False)
    op.create_index('ix_internal_links_source', 'internal_links', ['source_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_clusters_code', 'clusters', ['code'], unique=1)
    op.create_table('content_item_clusters',
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'cluster_id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keywords_keyword', 'keywords', ['keyword'], unique=1)
    op.create_table('content_keywords',
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'keyword_id')
    )
    op.create_table('gsc_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('clicks', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('impressions', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('ctr', sa.FLOAT(), nullable=True),
    sa.Column('position', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'date', name='uq_gsc_content_date')
    )
    # ### end Alembic commands ###
