"""index url+cluster_id; add timestamps to content_items

Revision ID: cd3e89114a5c
Revises: 53fe0cf91ebc
Create Date: 2025-08-22 13:33:13.655856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3e89114a5c'
down_revision: Union[str, Sequence[str], None] = '53fe0cf91ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
