name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install binary wheels for native deps
        run: |
          pip install --only-binary=:all: lxml==5.2.2 psycopg[binary]==3.2.3

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q